#!/bin/bash

URL=(
	http://mingw-w64.svn.sourceforge.net/svnroot/mingw-w64/trunk/mingw-w64-libraries/winpthreads
)

CFG=(
	--prefix=$DIR_BLD
	--enable-{static,shared}
)

#--disable-shared
