#!/bin/bash

URL=http://mirrors.webhostinggeeks.com/gcc/releases/gcc-4.7.2/gcc-4.7.2.tar.bz2

CFG=(
	--prefix=$DIR_BLD
	--with-sysroot=$DIR_REL
	--enable-version-specific-runtime-libs
	--with-pkgversion='MinGW-lite'
	--enable-targets=all
	--enable-checking=release
	--enable-{lto,libgomp,graphite,sjlj-exceptions}
	--enable-threads=posix
	--enable-languages=c,c++,lto
	--disable-{multilib,libstdcxx-pch,bootstrap,nls,win32-registry,rpath,werror,symvers}
	--with-{gmp,mpfr,mpc}=$DIR_DEP
)

#--with-bugurl=url
#--with-arch=i686
#--with-tune=generic
