#!/bin/bash

URL=(
	ftp://ftp.irisa.fr/pub/mirrors/gcc.gnu.org/gcc/releases/gcc-$GCC_VER/gcc-$GCC_VER.tar.bz2
)

EXC=gcc/testsuite

CFG=(
	--prefix=$DIR_BLD
	--with-sysroot=$DIR_REL
	--enable-version-specific-runtime-libs
	--with-pkgversion='MinGW-lite'
	--enable-targets=all
	--enable-checking=release
	--enable-threads=posix
	--enable-languages=c,c++,lto
	--enable-cxx-flags='-fomit-frame-pointer'
	--enable-{lto,libgomp,graphite,sjlj-exceptions}
	--disable-{multilib,static,libstdcxx-pch,bootstrap,nls,win32-registry,rpath,werror,symvers}
	--with-{gmp,mpfr,mpc}=$DIR_DEP
)

#--with-dwarf2

#--with-native-system-header-dir=
#  Specifies that dirname is the directory that contains native system header files, rather than /usr/include.
#  This option is most useful if you are creating a compiler that should be isolated from the system as much as possible.
#  It is most commonly used with the --with-sysroot option and will cause GCC to search dirname inside the system root specified by that option. 

#--with-bugurl=url
#--with-arch=i686
#--with-tune=generic
